#!/bin/sh
rm ../*.o
rm create_data_conf
rm test_db
rm test_index
#g++ -g ../posix.cc ../configure.cc ../kvs_slice.h ../kvs_status.cc create_data_conf.cc unit_func.cc -o create_data_conf
g++ -g ../posix.cc ../index.cc ../configure.cc ../kvs_slice.h ../kvs_status.cc test_index.cc unit_func.cc -o test_index
#g++ -g ../*.cc ../kvs_slice.h test_db.cc -o test_db
